version: "3.9"
services:
  app:
    build: .
    volumes:
      - ./static:/server/static
    ports:
      - "10000:10000"

  mysql:
    image: mysql/mysql-server:latest
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=12345678

  redis:
    image: redis
